title: QuantChi - —Årypto scanner
description: no-code tool to automate your trading strategies
theme: just-the-docs

url: https://quantchi.github.io

logo: "/assets/images/logo.svg"

footer_content: "Copyright &copy; 2024 quantchi.io"