title: QuantChi - —Årypto scanner
description: no-code tool to automate your trading strategies
theme: just-the-docs

url: https://docs.quantchi.io

logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicons/favicon-256.png"


footer_content: "Copyright &copy; 2024 quantchi.io"

search_enabled: false